### PR TITLE
Pass in domain via parameter

### PR DESCRIPTION
**Pull request by lpradovera**

### CODE REVIEW

**Comment by lpradovera** [comment]
@bryanrite take a look when it's convenient, please.

**Review by bryanrite — CHANGES_REQUESTED** [review]
ENV handling looks great, but bigger changes required for consistency, as discussed in Slack.

**Comment by lpradovera** [comment]
@bryanrite the named parameter was added too. Is that not what you meant?

**Comment by bryanrite** [comment]
I meant the discussion with @edolix regarding the consistency of initializers across the board has changed the requirements for this PR. Follow up with @edolix please!

**Comment by bryanrite** [comment]
@lpradovera Are we waiting for anything on this?

**Pull request merged**
