### PR TITLE
Replace the call namespace with calling

### PR DESCRIPTION
**Pull request by lpradovera**

### CODE REVIEW

**Comment by lpradovera** [comment]
https://github.com/signalwire/relay-apis/issues/100

**Comment by emcgee** [comment]
Wouldn’t this break backwards comparability?

**Comment by lpradovera** [comment]
This is at the Relay level, and the server side is already backwards compatible as per the discussion in here: https://github.com/signalwire/relay-apis/issues/100

**Review by bryanrite — DISMISSED** [review]

**Comment by lpradovera** [comment]
@bryanrite re-approve please.

**Review by bryanrite — APPROVED** [review]

**Pull request merged**
